### ISSUE TITLE
Fill in text about performing automatic composition

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-ar-module#11]
https://immersive-web.github.io/webxr-ar-module/#automatic-composition

We should basically mention that the device will automatically compose the rendered scene on top of the real-world background as perceived by  its cameras, alpha blending the two layers on top of each other.

We should also mention that automatic composition is not responsible for dealing with occlusion: the rendered scene will always compose on top of the camera background.

**Comment by NellWaliczek** [comment]
Sounds like a good start.  We probably need to call out that this will be different on additive light displays.  And explicitly state that developers do not get camera access in either case.  WDYT?

**Comment by Manishearth** [comment]
Ah, right!

To be clear, do we consider what happens on additive light displays to be "automatic composition" as well? I can tweak the wording to cover both cases.

**Comment by NellWaliczek** [comment]
Personally, I've been considering it to be "implied" automatic composition ^_^

We should be cautious here though.  In a world where additive light displays add support for per-pixel dimming... well, we'll probably need to adjust our environment blend mode options, but if possible it'd be nice to have the composition text be flexible enough to handle it without changes.

**Comment by Manishearth** [comment]
I'll try to make that work!

**Comment by Manishearth** [comment]
#12
