### ISSUE TITLE
XRLayers should never be composited using 'lighter'

### ISSUE THREAD

**Issue by rcabanier** [immersive-web/webxr-ar-module#23]
The spec currently says:

> When performing additive environment blending, the rendered buffers obtained by the XR Compositor are composited using lighter blending before being presented on the XR device.

This is incorrect. On devices with additive blending the layers must be composited using `source-over` as usual. The result of that composition is then composited with the real world using `lighter`

**Comment by Manishearth** [comment]
https://github.com/immersive-web/webxr-ar-module/pull/25

**Comment by Manishearth** [comment]
@rcabanier could you make a PR that addresses this?

**Comment by Manishearth** [comment]
Closing since we're not quite sure what to do here.
