### ISSUE TITLE
Clarify `environmentBlendMode` semantics

### ISSUE THREAD

**Issue by klausw** [immersive-web/webxr-ar-module#3]
As per recent discussions on the public-immersive-web-wg list (see also immersive-web/webxr#786), I think it would be helpful to add some clarifications to the [environmentBlendMode](https://immersive-web.github.io/webxr/#dom-xrsession-environmentblendmode) section of the spec.

I'd suggest emphasizing that this is a read-only value that's set by the user agent based on the session mode and hardware properties, and that applications cannot change it or request a specific blend mode.

> Note: Most Virtual Reality devices exhibit "opaque" blending behavior. Augmented Reality devices that use transparent optical elements frequently exhibit "additive" blending behavior, and Augmented Reality devices that use passthrough cameras frequently exhibit "alpha-blend" blending behavior.

This note is a bit confusing now that the spec doesn't include `immersive-ar`. How about including something similar to this instead?

Sessions of type `inline` and `immersive-vr` MUST use the blending mode most effective for making the user's environment not visible. This is _opaque_ mode when possible, but a headset with an optical see-through display MAY choose _additive_ if the hardware is not capable of _opaque_ mode. Applications can use the reported _additive_ blend mode to adjust color choices if necessary to help support this fallback VR mode.

The blend mode of _alpha-blend_ is reserved for future extensions such as augmented reality on a device using passthrough camera, this MUST NOT be used for `inline` and `immersive-vr` sessions.

**Comment by NellWaliczek** [comment]
Fixed by #2
