### ISSUE TITLE
[editorial] Prepare for FPWD

### ISSUE THREAD

**Issue by himorin** [immersive-web/webxr-ar-module#30]
For publishing as FPWD, we need to 

- [ ] state in status about the document is split-off from WebXR Device API
- [ ] modify publication date and document status as FPWD
- [x] modify (or confirm?) the abstract, current one seems to be the same text as WebXR Device API

Let me file PR(s) for proposal (on first two).

@dontcallmedom if i miss something, please let me know via comment(s).

**Comment by Manishearth** [comment]
This seems to be fixed, thanks!
