### ISSUE TITLE
Interoperability and compatibility - browser vendors & web developers support

### ISSUE THREAD

**Issue by bialpio** [immersive-web/webxr-ar-module#46]
I'm currently preparing to send out an Intent to Ship for WebXR AR Module so I'd like to poll for other vendors' support for the module. @thetuvix, @Manishearth, @grorg, @rcabanier - can you share your opinion?

Web developers' opinion about this module is also welcome!

**Comment by Manishearth** [comment]
Servo has this implemented for two devices, so we're +1 on this.

**Comment by thetuvix** [comment]
Ship it!  The AR module is key for targeting WebXR content at HoloLens and Mozilla has already implemented it with success in Firefox Reality.

**Comment by Manishearth** [comment]
triage: closing, folks can keep discussing here if they wish
