### ISSUE TITLE
Solutions for camera pose estimation in AR scene on Phone

### ISSUE THREAD

**Issue by Simon1059770342** [immersive-web/webxr-ar-module#80]
A bit curious about the solution for camera pose estimation in AR scene on Phone.

For the best of my knowledge, I supposed monocular camera on phone usually take 2 steps to achieve the goal：(take a feature as an example)

1. Estimate a normalized 3D coordinate between two continuous frames, the result could also hint the direaction from camera to a feature on target.
2. Leverage Triangulation to work out the deepth between camera and a feature on target.
3. Combine Direction, normalized 3D coordinate from Step1 and Deepth from Stpe2 to gain a final 3D coordinate of the feature on target.

The aim is to get 3D coordinate of the feature on target in camera coordinate system.

AM I RIGHT or NOT?

THX for the HELP!

**Comment by AdaRoseCannon** [comment]
The way the device pose is achieved is left up to the user agent and how it uses the hardware on device.
Some devices have specialised hardware, some use computer vision like you say.

Please stop opening endless issues.

**Comment by Simon1059770342** [comment]
THX a lot! 

Sorry! I didnt no this is Not a place to ask question. 

Here is the only palce that I can pop out WebXR immersive-ar questions I suppose. 

No one answer my question in [discourse.threejs.org](https://discourse.threejs.org/).

Or anyone could share a place for question discuss, that will be really kind! THX!

**Comment by AdaRoseCannon** [comment]
The WebXR Discord is pretty active.

I am thinking on making a new repo here for developer questions, just
getting feedback from others to make sure they are okay with it, if that
opens up feel free to ask in the issues there.

Ada

**Comment by Simon1059770342** [comment]
Great！THX Ada for you Patience and Kindness！

**Comment by Simon1059770342** [comment]
THX again! I will keep your words and pop out questions in WebXR Discord instead of here.
